### ISSUE TITLE
ModuleNotFoundError: No module named 'scrapy_user_agents'

### ISSUE THREAD

**Issue by h1david96** [spandanpal22/Web_Scraping_Amazon#1]
I'm getting this error when i try to run the spider "scrapy crawl spider".

**Comment by spandanpal22** [comment]
You have to run the spider by the command "scrapy crawl amazon_spider" as in the spider folder in amazon_spider.py file I have named the spider as amazon_spider. And don't forget to run it on a python virtual environment. I have given the required packages in the requirements.txt file. And run this command inside the folder amazonScraping.
